name: Ruby
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  macos_regression:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby:
          - 3.1.6
          - 3.2.6
          - 3.3.6
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
  ubuntu_regression:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.1.6
          - 3.2.6
          - 3.3.6
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
